# Generated by Django 5.2.1 on 2025-05-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Assignees',
            },
        ),
        migrations.AlterField(
            model_name='contacts',
            name='password',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('prio', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('toDos', "To Do's"), ('inProgress', 'In Progress'), ('awaitFeedback', 'Awaiting Feedback'), ('done', 'Done')], default='toDos', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('assignee_infos', models.ManyToManyField(blank=True, related_name='tasks', to='backend.assignee')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtasktext', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='backend.task')),
            ],
            options={
                'verbose_name_plural': 'Subtasks',
            },
        ),
    ]
