# Generated by Django 5.2.1 on 2025-05-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_assignee_alter_contacts_password_task_subtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignee',
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee_infos',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='backend.contacts'),
        ),
    ]
