# Generated by Django 5.2.1 on 2025-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_assignee_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
