# Generated by Django 5.2.1 on 2025-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_task_task_id_alter_contacts_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('urgent', 'Hoch')], default='medium', max_length=20),
        ),
    ]
